name: bengine-cli

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_RELEASE }}
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm ci
      - run: npm test

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main')
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_RELEASE }}
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
      - run: npm ci
      - run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_RELEASE }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
